config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  resources :posts do
    resources :comments, only: :create
    # resources :likes, only: [:create, :destroy]
  end
  resources :users, only: :show do
    collection do
      get :likes
    end
  end


  get "chest" => "menus#chest"
  get "back" => "menus#back"
  get "shoulder" => "menus#shoulder"
  get "arm" => "menus#arm"
  get "leg" => "menus#leg"
  get "trunk" => "menus#trunk"
  get "food" => "menus#food"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id: 1, name: '--'},
    {id: 2, name: '胸'},
    {id: 3, name: '背中'},
    {id: 4, name: '肩'},
    {id: 5, name: '腕'},
    {id: 6, name: '脚'},
    {id: 7, name: '腹筋'},
    {id: 8, name: '食事メニュー'}
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category

  mount_uploader :video, VideoUploader
  
  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  with_options presence: true do
    validates :name,        length: { maximum: 20 }
    validates :description, length: { maximum: 140 }
    validates :category_id, numericality: { other_than: 1 }
    validates :video
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  
  PASSWORD_REGEX = /\A[a-zA-Z0-9]+\z/
  
  with_options presence: true do
    validates :nickname, length: { maximum: 10 }
    validates :email
    validates :password, length: { minimum: 6 }, format: {with: PASSWORD_REGEX}
    validates :password_confirmation, length: { minimum: 6 }, format: {with: PASSWORD_REGEX}
  end

  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email,
    :password, :password_confirmation])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :post_params

  def create
    @like = Like.create(user_id: current_user.id, post_id: @post.id)
  end
  
  def destroy
    @like = Like.find_by(user_id: current_user.id, post_id: @post.id).destroy
  end

  private

  def post_params
    @post = Post.find(params[:id])
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!
  
  def chest
    @posts = Post.where(category_id: 2).order("created_at DESC")
  end

  def back
    @posts = Post.where(category_id: 3).order("created_at DESC")
  end

  def shoulder
    @posts = Post.where(category_id: 4).order("created_at DESC")
  end

  def arm
    @posts = Post.where(category_id: 5).order("created_at DESC")
  end

  def leg
    @posts = Post.where(category_id: 6).order("created_at DESC")
  end

  def trunk
    @posts = Post.where(category_id: 7).order("created_at DESC")
  end

  def food
    @posts = Post.where(category_id: 8).order("created_at DESC")
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, except: [:index, :show]

  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  private
  def post_params
    params.require(:post).permit(:name, :description, :category_id, :video, :likes_count).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = Usr.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @posts = Post.includes(:user).order("created_at DESC")
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>筋コミ</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="wrapper">
    <div id="navArea">
      <nav>
        <div class="inner">
          <% if user_signed_in? %>
            <ul>
              <li>
                <%= link_to "/users/#{current_user.id}", method: :GET do %>
                  <%= current_user.nickname %>
                <% end %>
              </li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
              <li><%= link_to '投稿する', '/posts/new', class: 'post', method: :GET %></li>
              <li><%= link_to '# いいね!した投稿', likes_users_path, class: 'menu' %></li>
              <li><%= link_to '# 胸の日', chest_path, class: 'menu' %></li>
              <li><%= link_to '# 背中の日', back_path, class: 'menu' %></li>
              <li><%= link_to '# 肩の日', shoulder_path, class: 'menu' %></li>
              <li><%= link_to '# 腕の日', arm_path, class: 'menu' %></li>
              <li><%= link_to '# 脚の日', leg_path, class: 'menu' %></li>
              <li><%= link_to '# 腹筋の日', trunk_path, class: 'menu' %></li>
              <li><%= link_to '# 食事メニュー', food_path, class: 'menu' %></li>
            </ul>
          <% else %>
            <ul>
              <li><%= link_to 'ログイン', new_user_session_path, class: 'post' %></li>
              <li><%= link_to 'サインアップ', new_user_registration_path, class: 'post' %></li>
            </ul>
          <% end %>
        </div>
      </nav>
    </div>
    <main>
      <%= yield %>
    </main>
  </div>
</body>
</html>

app/views/likes/create.js.erb
//$(".post_<%= @post.id %>").html("<%= j(render 'posts/post', post: @post ) %>");

document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j(render @post) %>'

app/views/likes/destroy.js.erb
//$(".post_<%= @post.id %>").html("<%= j(render 'posts/post', post: @post ) %>");

document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j(render @post) %>'

app/views/menus/abs.html.erb
<header>
  <div class="header-inner">
    <div>腹筋トレの投稿</div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<div class="center-contents-index">
  <div class="post-space-index">
    <% @posts.each do |post| %>
      <div id="post_<%= post.id %>">
        <%= render 'posts/post', post: post %>
      </div>
    <% end %>
  </div>
</div>

app/views/menus/arm.html.erb
<header>
  <div class="header-inner">
    <div class="toggle_btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div id="mask"></div>
    <div class="header-inner-title">腕トレの投稿</div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<%= render 'posts/posts', post: @post %>

app/views/menus/back.html.erb
<header>
  <div class="header-inner">
    <div class="toggle_btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div id="mask"></div>
    <div class="header-inner-title">背中トレの投稿</div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<%= render 'posts/posts', post: @post %>

app/views/menus/chest.html.erb
<header>
  <div class="header-inner">
    <div class="toggle_btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div id="mask"></div>
    <div class="header-inner-title">胸トレの投稿</div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<%= render 'posts/posts', post: @post %>

app/views/menus/food.html.erb
<header>
  <div class="header-inner">
    <div class="toggle_btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div id="mask"></div>
    <div class="header-inner-title">食事メニューの投稿</div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<%= render 'posts/posts', post: @post %>

app/views/menus/leg.html.erb
<header>
  <div class="header-inner">
    <div class="toggle_btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div id="mask"></div>
    <div class="header-inner-title">脚トレの投稿</div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<%= render 'posts/posts', post: @post %>

app/views/menus/shoulder.html.erb
<header>
  <div class="header-inner">
    <div class="toggle_btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div id="mask"></div>
    <div class="header-inner-title">肩トレの投稿</div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<%= render 'posts/posts', post: @post %>

app/views/menus/trunk.html.erb
<header>
  <div class="header-inner">
    <div class="toggle_btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div id="mask"></div>
    <div class="header-inner-title">腹筋トレの投稿</div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<%= render 'posts/posts', post: @post %>

app/views/posts/_post.html.erb
<div class="posts">
  <%= link_to '', post_path(post.id), method: :get %>

  <div class="post-top">
    <div class="weight-bold-text-index">
      <%= post.user.nickname %>
    </div>
    <%= post.created_at.strftime('%Y/%m/%d %H:%M') %>
  </div>

  <% if post.video? %>
    <% if post.video.file.content_type.include?('video/') %>
      <div class="training-name">トレーニング名: <%= post.name %></div>
    <% else %>
      <div class="training-name">食事名: <%= post.name %></div>
    <% end %>
  <% end %>
</div>
<div class="like-btn-space">
  <% if current_user.liked_by?(post.id) %>
    <%= link_to 'いいね!', destroy_like_path(post), class: "unlike-btn", method: :DELETE, remote: true %>
  <% else %>
    <%= link_to 'いいね!', create_like_path(post), class: "like-btn", method: :POST, remote: true %>
  <% end %>
  <div class="like-count"><%= post.likes.count %></div>
</div>
<div class="video">
  <% if post.video? %>
    <% if post.video.file.content_type.include?('video/') %>
      <%= video_tag post.video.to_s, loop: true, controls: true, :playsinline => 'true', class: "video embed-responsive-post" %>
    <% else %>
      <%= image_tag post.video.to_s, class: "video embed-responsive-post" %>
    <% end %>
  <% end %>
</div>
<hr>

app/views/posts/_posts.html.erb
<% if @posts.exists? %>
  <div class="center-contents-index">
    <div class="post-space-index">
      <% @posts.each do |post| %>
        <div id="post_<%= post.id %>">
          <%= render 'posts/post', post: post %>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="center-contents-index">
    <div class="post-space-index">
      <div class="post-none">
        <%= link_to '投稿してね!!', '/posts/new', method: :GET %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<header>
  <div class="header-inner">
    <div class="toggle_btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div id="mask"></div>
    <div class="header-inner-title">編集する</div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<div class="center-contents-new">
  <div class="post-create">
    <%= form_with model: @post, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="weight-bold-text">
        トレーニング名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :name, class:"posts-text", placeholder:"トレーニング名", maxlength:"20" %>
      <div class="weight-bold-text">
        トレーニング説明
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :description, class:"posts-text", placeholder:"トレーニング説明", rows: "5", maxlength:"140" %>
      <div class="weight-bold-text">
        カテゴリー
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
      <div class="weight-bold-text">
        投稿する動画
        <span class="indispensable">必須</span>
      </div>
      <%= f.label :video %>
      <%= f.file_field :video, :accept => 'video/*, image/*' %>
      <div class="post-btn-contents">
        <%= f.submit "編集", class:"post-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<header>
  <div class="header-inner">
    <div class="toggle_btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div id="mask"></div>
    <div class="header-inner-title">新着投稿</div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<%= render 'posts/posts', post: @post %>

app/views/posts/new.html.erb
<header>
  <div class="header-inner">
    <div class="toggle_btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div id="mask"></div>
    <div class="header-inner-title">投稿する</div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<div class="center-contents-new">
  <div class="post-create">
    <%= form_with model: @post, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="weight-bold-text">
        トレーニング名/食事名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :name, class:"posts-text", placeholder:"トレーニング名/食事名", maxlength:"20" %>
      <div class="weight-bold-text">
        トレーニング説明/食事名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :description, class:"posts-text", placeholder:"トレーニング説明/食事説明", rows: "5", maxlength:"140" %>
      <div class="weight-bold-text">
        カテゴリー
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
      <div class="weight-bold-text">
        投稿する動画
        <span class="indispensable">必須</span>
      </div>
      <%= f.label :video %>
      <%= f.file_field :video, :accept => 'video/*, image/*' %>
      <div class="post-btn-contents">
        <%= f.submit "投稿", class:"post-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<header>
  <div class="header-inner">
    <div>
      <div class="toggle_btn">
        <span></span>
        <span></span>
        <span></span>
      </div>
      <div id="mask"></div>
      <a href="/users/<%= @post.user.id %>" class="header-inner-title">
        <%= @post.user.nickname %>さん
      </a>
      の投稿
    </div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<div class="center-contents-show">
  <div class="post-space-show">
    <div class="posts-show">
      <div class="video-space">
        <p>
          <% if @post.video? %>
            <% if @post.video.file.content_type.include?('video/') %>
              <%= video_tag @post.video.to_s, loop: true, controls: true, :playsinline => 'true', class: "video embed-responsive-post" %>
            <% else %>
              <%= image_tag @post.video.url %>
            <% end %>
          <% end %>
        </p>
      </div>
      <div class="post-mid">
        <% if @post.video? %>
          <% if @post.video.file.content_type.include?('video/') %>
            <div class="weight-bold-text">トレーニング名:</div>
          <% else %>
            <div class="weight-bold-text">食事名:</div>
          <% end %>
        <% end %>
        <%= @post.created_at.strftime('%Y/%m/%d %H:%M') %>
      </div>
      <%= @post.name %>
      <div class="weight-bold-text">
        説明:
      </div>
      <%= @post.description %>
      <div class="weight-bold-text">
        カテゴリー:
      </div>
      <%= @post.category.name %>
    </div>
    <% if user_signed_in? && current_user.id == @post.user_id %>
      <div class="more-show">
          <%= link_to '編集', edit_post_path(@post.id), class:"edit-btn", method: :get %>
          <%= link_to '削除', post_path(@post.id), class:"delete-btn", method: :delete %>
      </div>
    <% end %>
    <div class="weight-bold-text">
      コメント:
    </div>
    <div class="messages">
      <div class="message">
        <% if @comments %>
          <% @comments.each do |comment| %>
            <p>
              <strong><%= comment.user.nickname %>:</strong>
              <%= comment.text %>
            </p>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= form_with(model: [@post, @comment], local: true) do |form| %>
      <div class="form">
        <div class="form-input">
          <div class="form-message">
            <%= form.text_field :text, placeholder: "コメントする", rows: "2" %>
          </div>
        </div>
        <div class="form-submit">
          <%= form.submit "送信" %>
        </div>
      </div>
    <% end %>
  </div>
</div> 

app/views/users/likes.html.erb
<header>
  <div class="header-inner">
    <div class="toggle_btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div id="mask"></div>
    <div class="header-inner-title">いいね!した投稿</div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<% if current_user.liked_posts.exists? %>
  <div class="center-contents-index">
    <div class="post-space-index">
      <% current_user.liked_posts.each do |post| %>
        <div id="post_<%= post.id %>">
          <%= render 'posts/post', post: post %>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="post-none">
    <div class="center-contents-index">
      <div class="post-space-index">
        <%= link_to '投稿をいいねしよう!!', root_path %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<header>
  <div class="header-inner">
    <div class="toggle_btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div id="mask"></div>
    <div class="header-inner-title">
      <%= @nickname %>さんの投稿一覧
    </div>
    <%= link_to image_tag("kinkomilogo2.png", class:"top-page"), "/" %>
  </div>
</header>
<%= render 'posts/posts', post: @post %>